__base__:
    - ../default_runtime.yaml
    - ../datasets/DualCervix/DualCervixRegistration/DualCervixRegistration_color.yaml
    - ../models/GAN/CycleGAN.yaml

trainer:
    logger:
        init_args:
            name: cycle_gan_ResnetGenerator_NLayerDiscriminator_color
    # debug
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    limit_test_batches: 1.0
    limit_predict_batches: 1.0
    fast_dev_run: false
    overfit_batches: 0.0
    # train
    max_epochs: null
    min_epochs: null
    max_steps: -1
    min_steps: null
    max_time: null
    # gradient clip
    gradient_clip_val: null
    gradient_clip_algorithm: null
    # gpus
    strategy: ddp

data:
    init_args:
        data_loader_config:
            batch_size: 1
            num_workers: 3
            prefetch_factor: 2
