model:
    class_path: models.models.vxm_dense.VxmDense
    init_args:
        backbone:
            class_path: models.backbones.Unet.Unet
            init_args:
                inshape: [ 608, 608 ]
                infeats: 2
        inshape: [ 608, 608 ]
        final_nf: 16
        loss_config:
            img:
                type: NCC
                weight: 1.0
            grad:
                type: Grad
                param:
                    penalty: 2
                weight: 1.0
            seg:
                type: Dice
                weight: 1.0
        optimizer_config:
            optimizer:
                type: AdamW
                lr: 1.0e-3
                weight_decay: 0.01
            lr_scheduler:
                scheduler:
                    type: ReduceLROnPlateau
                    mode: min
                    factor: 0.1
                    patience: 5
                    cooldown: 2
                monitor: train/loss
                warmup_config:
                    warmup_iters: 500