model:
    class_path: models.networks.VxmDense
    init_args:
        inshape: [ 608, 928 ]
        src_feats: 3
        trg_feats: 3
        loss_config:
            img:
                type: NCC
                weight: 10.0
            grad:
                type: 2
                weight: 1000.0
            seg:
                weight: 1.0
        optimizer_config:
            optimizer:
                type: Adam
                lr: 3.0e-3
                weight_decay: 0.0001
            lr_scheduler:
                scheduler:
                    type: ReduceLROnPlateau
                    mode: min
                    factor: 0.1
                    patience: 5
                    cooldown: 2
                monitor: train/loss
data:
    class_path: datasets.DualCervix.DualCervixDataModule
    init_args:
        ann_path: hsil_rereannos
        train_pipeline:
            -   type: LoadImageFromFile
            -   type: LoadAnnotations
                with_bbox: true
            -   type: Resize
                img_scale: &import_img_scale [ 928, 608 ]
                keep_ratio: false
            -   type: Pad
                size_divisor: 32
            -   type: RandomFlip
                flip_ratio: 0.5
            -   type: Normalize
                # mean: {'acid': [97.57475280761719, 102.059326171875, 143.3719024658203], 'iodine': [60.97126388549805, 87.94377136230469, 133.1758270263672]}
                # std: {'acid': [45.371376037597656, 43.705657958984375, 51.12405776977539], 'iodine': [59.728607177734375, 63.77861404418945, 69.6864013671875]}
                mean: &import_norm_cfg_mean [ 79.2785873413086, 95.04068756103516, 138.40469360351562 ]
                std: &import_norm_cfg_std [ 56.09214782714844, 55.104705810546875, 61.23152542114258 ]
                to_rgb: true
            -   type: GenSegmentationFromBBox
                num_classes: 2
            -   type: DefaultFormatBundle
            -   type: Collect
                keys: [ img, gt_bboxes, gt_labels, gt_segments_from_bboxes ]
        test_pipeline:
            -   type: LoadImageFromFile
            -   type: MultiScaleFlipAug
                img_scale: *import_img_scale
                flip: false
                transforms:
                    -   type: Resize
                        keep_ratio: false
                    -   type: Pad
                        size_divisor: 32
                    -   type: RandomFlip
                    -   type: Normalize
                        mean: *import_norm_cfg_mean
                        std: *import_norm_cfg_std
                        to_rgb: true
                    -   type: GenSegmentationFromBBox
                        num_classes: 2
                    -   type: DefaultFormatBundle
                    -   type: Collect
                        keys: [ img, gt_bboxes, gt_labels, gt_segments_from_bboxes ]
        data_root: data/DualCervixDetection
        img_prefix: img
        batch_size: 16
        num_workers: 16
trainer:
    logger:
        class_path: utils.loggers.wandb.WandbNamedLogger
        init_args:
            name: dual_cervix_registration
            project: dual_cervix_registration
            offline: false
    callbacks:
        -   class_path: pytorch_lightning.callbacks.LearningRateMonitor
            init_args:
                logging_interval: null
                log_momentum: true
        -   class_path: utils.callbacks.wandb_logger_watch_model_callback.WandbLoggerWatchModelCallback
            init_args:
                log: all
                log_graph: true
        -   class_path: utils.progress.rich_progress.RichDefaultThemeProgressBar
        -   class_path: pytorch_lightning.callbacks.RichModelSummary
            init_args:
                max_depth: 2
        -   class_path: pytorch_lightning.callbacks.ModelCheckpoint
            init_args:
                monitor: val/loss
                filename: 'epoch={epoch}-val_loss={val/loss}'
                save_top_k: 3
                save_last: true
                mode: min
                auto_insert_metric_name: false
    # debug
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    limit_test_batches: 1.0
    limit_predict_batches: 1.0
    fast_dev_run: false
    overfit_batches: 0.0
    # train
    max_epochs: null
    min_epochs: null
    max_steps: -1
    min_steps: null
    max_time: null
    # gradient clip
    gradient_clip_val: null
    gradient_clip_algorithm: null
    # path
    weights_save_path: work_dirs
    # gpus
    num_nodes: 1
    num_processes: 1
    gpus: -1
    strategy: null
    sync_batchnorm: false
    # speed up
    precision: 32
    auto_lr_find: true
    detect_anomaly: true
    auto_scale_batch_size: false
    accumulate_grad_batches: null
    profiler: null
    # val and log
    check_val_every_n_epoch: 1
    val_check_interval: 1.0
    flush_logs_every_n_steps: null
    log_every_n_steps: 50
    track_grad_norm: -1
# check point
ckpt_path: null
# seed
seed_everything: null
