__base__: DualCervix_color.yaml

__import__:
    import_load_img_transform: &import_load_img_transform
        type: LoadImageFromFile
        color_type: grayscale

    import_img_scale: &import_img_scale
        img_scale: [ 512, 512 ]
    import_resize_transform: &import_resize_transform
        type: Resize
        <<: *import_img_scale
        keep_ratio: false

    import_acid_normalize_transform: &import_acid_normalize_transform
        type: Normalize
        mean: [ 122.95729064941406 ]
        std: [ 15.282942771911621 ]
        to_rgb: false
    import_iodine_normalize_transform: &import_iodine_normalize_transform
        type: Normalize
        mean: [ 83.96733856201172 ]
        std: [ 20.51559829711914 ]
        to_rgb: false

data:
    class_path: datasets.DualCervix.DualCervixDataModule
    init_args:
        pipeline:
            acid:
                -   <<: *import_load_img_transform
                -   type: LoadAnnotations
                    with_bbox: true
                -   <<: *import_resize_transform
                -   <<: *import_acid_normalize_transform
                -   type: RandomFlip
                    flip_ratio: 0.5
                -   type: GenSegmentationFromBBox
                    num_classes: 1
                -   type: DefaultFormatBundle
                -   type: Collect
                    keys: [ img, gt_bboxes, gt_labels, gt_segments_from_bboxes ]
            iodine:
                -   <<: *import_load_img_transform
                -   type: LoadAnnotations
                    with_bbox: true
                -   <<: *import_resize_transform
                -   <<: *import_iodine_normalize_transform
                -   type: RandomFlip
                    flip_ratio: 0.5
                -   type: GenSegmentationFromBBox
                    num_classes: 1
                -   type: DefaultFormatBundle
                -   type: Collect
                    keys: [ img, gt_bboxes, gt_labels, gt_segments_from_bboxes ]