model:
    class_path: models.models.mmdetectors.MMDetModelAdapter
    init_args:
        model:
            class_path: models.models.mmdetectors.TwoStageDetector
            init_args:
                backbone:
                    type: ResNet
                    depth: 50
                    frozen_stages: 1
                    norm_eval: true
                    num_stages: 4
                    out_indices: [ 0, 1, 2, 3 ]
                    style: pytorch
                    norm_cfg:
                        requires_grad: true
                        type: BN
                    init_cfg:
                        checkpoint: torchvision://resnet50
                        type: Pretrained
                neck:
                    type: FPN
                    in_channels: [ 256, 512, 1024, 2048 ]
                    num_outs: 5
                    out_channels: 256
                roi_head:
                    type: StandardRoIHead
                    bbox_roi_extractor:
                        type: SingleRoIExtractor
                        featmap_strides: [ 4, 8, 16, 32 ]
                        out_channels: 256
                        roi_layer:
                            type: RoIAlign
                            output_size: 7
                            sampling_ratio: 0
                    bbox_head:
                        type: Shared2FCBBoxHead
                        fc_out_channels: 1024
                        in_channels: 256
                        num_classes: 80
                        reg_class_agnostic: false
                        roi_feat_size: 7
                        bbox_coder:
                            type: DeltaXYWHBBoxCoder
                            target_means: [ 0.0, 0.0, 0.0, 0.0 ]
                            target_stds: [ 0.1, 0.1, 0.2, 0.2 ]
                        loss_bbox:
                            type: L1Loss
                            loss_weight: 1.0
                        loss_cls:
                            type: CrossEntropyLoss
                            loss_weight: 1.0
                            use_sigmoid: false
                rpn_head:
                    type: RPNHead
                    anchor_generator:
                        type: AnchorGenerator
                        ratios: [ 0.5, 1.0, 2.0 ]
                        scales: [ 8 ]
                        strides: [ 4, 8, 16, 32, 64 ]
                    bbox_coder:
                        type: DeltaXYWHBBoxCoder
                        target_means: [ 0.0, 0.0, 0.0, 0.0 ]
                        target_stds: [ 0.1, 0.1, 0.2, 0.2 ]
                    feat_channels: 256
                    in_channels: 256
                    loss_bbox:
                        type: L1Loss
                        loss_weight: 1.0
                    loss_cls:
                        type: CrossEntropyLoss
                        loss_weight: 1.0
                        use_sigmoid: true
                train_cfg:
                    rcnn:
                        debug: false
                        pos_weight: -1
                        assigner:
                            type: MaxIoUAssigner
                            ignore_iof_thr: -1
                            match_low_quality: false
                            min_pos_iou: 0.5
                            neg_iou_thr: 0.5
                            pos_iou_thr: 0.5
                        sampler:
                            type: RandomSampler
                            add_gt_as_proposals: true
                            neg_pos_ub: -1
                            num: 512
                            pos_fraction: 0.25
                    rpn:
                        allowed_border: -1
                        debug: false
                        pos_weight: -1
                        assigner:
                            type: MaxIoUAssigner
                            ignore_iof_thr: -1
                            match_low_quality: true
                            min_pos_iou: 0.3
                            neg_iou_thr: 0.3
                            pos_iou_thr: 0.7
                        sampler:
                            type: RandomSampler
                            add_gt_as_proposals: false
                            neg_pos_ub: -1
                            num: 256
                            pos_fraction: 0.5
                    rpn_proposal:
                        max_per_img: 1000
                        min_bbox_size: 0
                        nms:
                            iou_threshold: 0.7
                            type: nms
                        nms_pre: 2000
                test_cfg:
                    rcnn:
                        max_per_img: 100
                        nms:
                            type: nms
                            iou_threshold: 0.5
                        score_thr: 0.05
                    rpn:
                        max_per_img: 1000
                        min_bbox_size: 0
                        nms:
                            type: nms
                            iou_threshold: 0.7
                        nms_pre: 1000